apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: {{ .Release.Namespace }}
data:
  vsphere.conf: |
    [Global]
    secret-name = "vsphere-cpi-creds"
    secret-namespace = {{ .Release.Namespace | quote }}
    port = {{ .Values.vcenter.port | default "443" | quote }}
    insecure-flag = {{ .Values.vcenter.insecureflag | default "1" | quote }}

    [VirtualCenter {{ .Values.vcenter.host | quote }}]
    datacenters = {{ .Values.vcenter.datacenter | quote }}

