apiVersion: v1
kind: Secret
metadata:
  name: vsphere-cpi
  namespace: {{ .Release.Namespace }}
stringData:
  {{ .Values.vcenter.host }}.username: {{ .Values.vcenter.username }}
  {{ .Values.vcenter.host }}.password: {{ .Values.vcenter.password }}